In [40]:
# import numpy as np

# Create the numpy array from 1 to 10
arr = np.arange(1, 11)



In [18]:
reshaped_arr = arr.reshape(2,5 )
print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
arr = np.arange(1,21)

subset = arr[5:15]
print(subset)

[ 6  7  8  9 10 11 12 13 14 15]


In [32]:
import pandas as pd


fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})


fruits['pears'] = 4
print(fruits)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [34]:
data = {
    'name': ['Ardra', 'Sageer', 'Dinesh', 'Arun', 'Sukumari', 'Francis', 'Grace', 'Helen', 'Sundari', 'Deepak'],
    'age': [24, 30, 35, 40, 22, 28, 33, 26, 31, 29],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M']
}

df = pd.DataFrame(data)
print(df)


       name  age gender
0     Ardra   24      F
1    Sageer   30      M
2    Dinesh   35      M
3      Arun   40      M
4  Sukumari   22      F
5   Francis   28      M
6     Grace   33      F
7     Helen   26      F
8   Sundari   31      F
9    Deepak   29      M


In [36]:
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

df['occupation'] = occupations
print(df)


       name  age gender  occupation
0     Ardra   24      F  Programmer
1    Sageer   30      M     Manager
2    Dinesh   35      M     Analyst
3      Arun   40      M  Programmer
4  Sukumari   22      F     Manager
5   Francis   28      M     Analyst
6     Grace   33      F  Programmer
7     Helen   26      F     Manager
8   Sundari   31      F     Analyst
9    Deepak   29      M  Programmer


In [38]:
filtered_df = df[df['age'] >= 30]
print(filtered_df)


      name  age gender  occupation
1   Sageer   30      M     Manager
2   Dinesh   35      M     Analyst
3     Arun   40      M  Programmer
6    Grace   33      F  Programmer
8  Sundari   31      F     Analyst


In [42]:
df.to_csv('data.csv', index=False)

read_df = pd.read_csv('data.csv')
print(read_df)


       name  age gender  occupation
0     Ardra   24      F  Programmer
1    Sageer   30      M     Manager
2    Dinesh   35      M     Analyst
3      Arun   40      M  Programmer
4  Sukumari   22      F     Manager
5   Francis   28      M     Analyst
6     Grace   33      F  Programmer
7     Helen   26      F     Manager
8   Sundari   31      F     Analyst
9    Deepak   29      M  Programmer
